services:
  - name: python-app
    type: web
    env: python
    buildCommand: "cd python-app && pip install -r requirements.txt"
    startCommand: "cd python-app && gunicorn app:app"  # Python start command

  - name: php-app
    type: web
    env: php
    buildCommand: "cd php-app"
    startCommand: "php -S 0.0.0.0:10000 -t /php-app"  # PHP start command